Traceback (most recent call last):
  File "scripts/uts.py", line 32, in <module>
    main()
  File "/home/mhall/.local/share/virtualenvs/under-the-surface-4zrWpJKo/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/mhall/.local/share/virtualenvs/under-the-surface-4zrWpJKo/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mhall/.local/share/virtualenvs/under-the-surface-4zrWpJKo/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mhall/.local/share/virtualenvs/under-the-surface-4zrWpJKo/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mhall/.local/share/virtualenvs/under-the-surface-4zrWpJKo/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mhall/.local/share/virtualenvs/under-the-surface-4zrWpJKo/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mhall/Projects/under-the-surface/scripts/dta_link.py", line 19, in link_dta_data
    link_person(dbsession, person, db_property.value.value)
  File "/home/mhall/Projects/under-the-surface/scripts/dta_link.py", line 28, in link_person
    print(doc.getroot().xpath("//div[@id='meta-results-short']"))
AttributeError: 'lxml.etree._Element' object has no attribute 'getroot'
